version: '3.8'
services:
  db:
    container_name: turing-sec-db
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ../../docker-volumes/turing-sec-db:/var/lib/postgresql/data
